//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiDeposu.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLDERS
    {
        public int DERSID { get; set; }
        public string DERSAD { get; set; }
        public string DERSBOLUM { get; set; }
    }
}
