//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgiDeposu.Models.Entitiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKITAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKITAP()
        {
            this.TBLHAREKET = new HashSet<TBLHAREKET>();
            this.TBLNOTLAR = new HashSet<TBLNOTLAR>();
        }
    
        public int ID { get; set; }
        public string AD { get; set; }
        public Nullable<byte> KATEGORI { get; set; }
        public string SAYFA { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public string KITAPRESIM { get; set; }
        public string AKTS { get; set; }
        public Nullable<int> AKADEM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLHAREKET> TBLHAREKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLNOTLAR> TBLNOTLAR { get; set; }
        public virtual TBLAKADEMISYEN TBLAKADEMISYEN { get; set; }
        public virtual TBLAKADEMISYEN TBLAKADEMISYEN1 { get; set; }
        public virtual TBLBOLUM TBLBOLUM { get; set; }
    }
}
